/*******************************************************************
 * @Author 		 Dhruv Satasiya
 * @Date   		 August 09, 2025
 * @File   		 main.c
 * @Description  This project is to receive the data from the terminal
 * 				 and convert them to upper case format and transmit them
 * 				 back to the terminal using non-bloking(interrupt) based
 * 				 approach.
 * *****************************************************************/

/* Includes ------------------------------------------------------------------*/
#include "main.h"

/* Private variables ---------------------------------------------------------*/
GPIO_InitTypeDef hgpio;
UART_HandleTypeDef huart;

char msg[] = "I am Dhruv!!\r\n";   //message buffer stored with raw stirng, goes to .data segment of Stake memory of SRAM
uint8_t rcvd_byte;
char receive_buff[100];
uint16_t count = 0;

/* Private function prototypes -----------------------------------------------*/
void SystemClock_Config(void);
void GPIO_Init(void);
void UART_Init(void);
char upper_case(char);

/**
  * @brief  The application entry point.
  * @retval int
  */
int main(void)
{
  /* MCU Configuration--------------------------------------------------------*/
  /* Reset of all peripherals, Initializes the Flash interface and the Systick. */
  HAL_Init();
  
  /* Configure the system clock */
  SystemClock_Config();

  /* Initialize all configured peripherals */
  GPIO_Init();
  UART_Init();
  
  /* Receiving data over UART*/
  if( HAL_UART_Receive_IT(&huart, &rcvd_byte, (uint8_t)1) != HAL_OK)
   {
  	  Error_Handler();
   }

  /* Infinite loop */
  while (1)
  {
	  /* Do nothing but Do not remove this infinite function as
	   * it is the heart of the MCU to keep running the certain
	   * application forever.
	   * */
  } //eo indefinite while loop

} //eo main::

/**
  * @brief System Clock Configuration
  * @param None
  * @retval None
  * @note This function is automatically generated by the STM32CubeMX Software
          to initialize necessary clock configurations.
  */
void SystemClock_Config(void)
{
  RCC_OscInitTypeDef RCC_OscInitStruct = {0};
  RCC_ClkInitTypeDef RCC_ClkInitStruct = {0};

  /** Configure the main internal regulator output voltage
  */
  __HAL_RCC_PWR_CLK_ENABLE();
  __HAL_PWR_VOLTAGESCALING_CONFIG(PWR_REGULATOR_VOLTAGE_SCALE1);

  /** Initializes the RCC Oscillators according to the specified parameters
  * in the RCC_OscInitTypeDef structure.
  */
  RCC_OscInitStruct.OscillatorType = RCC_OSCILLATORTYPE_HSI;
  RCC_OscInitStruct.HSIState = RCC_HSI_ON;
  RCC_OscInitStruct.HSICalibrationValue = RCC_HSICALIBRATION_DEFAULT;
  RCC_OscInitStruct.PLL.PLLState = RCC_PLL_ON;
  RCC_OscInitStruct.PLL.PLLSource = RCC_PLLSOURCE_HSI;
  RCC_OscInitStruct.PLL.PLLM = 8;
  RCC_OscInitStruct.PLL.PLLN = 50;
  RCC_OscInitStruct.PLL.PLLP = RCC_PLLP_DIV4;
  RCC_OscInitStruct.PLL.PLLQ = 7;
  if (HAL_RCC_OscConfig(&RCC_OscInitStruct) != HAL_OK)
  {
    Error_Handler();
  }

  /** Initializes the CPU, AHB and APB buses clocks
  */
  RCC_ClkInitStruct.ClockType = RCC_CLOCKTYPE_HCLK|RCC_CLOCKTYPE_SYSCLK
                              |RCC_CLOCKTYPE_PCLK1|RCC_CLOCKTYPE_PCLK2;
  RCC_ClkInitStruct.SYSCLKSource = RCC_SYSCLKSOURCE_PLLCLK;
  RCC_ClkInitStruct.AHBCLKDivider = RCC_SYSCLK_DIV1;
  RCC_ClkInitStruct.APB1CLKDivider = RCC_HCLK_DIV4;
  RCC_ClkInitStruct.APB2CLKDivider = RCC_HCLK_DIV2;

  if (HAL_RCC_ClockConfig(&RCC_ClkInitStruct, FLASH_LATENCY_0) != HAL_OK)
  {
    Error_Handler();
  }
} //eo SystemClock_Config::

/**
  * @brief GPIO Initialization Function
  * @param None
  * @retval None
  * @note The GPIO initialization is solely done for debugging purpose, however, the
          application does not require any interaction with blinking LEDs or other. 
  */
void GPIO_Init(void)
{

	/*Enabling the clock for GPIOD*/
	__HAL_RCC_GPIOD_CLK_ENABLE();

	/*Configuring the general settings*/
	hgpio.Mode = GPIO_MODE_OUTPUT_PP;
	hgpio.Pull = GPIO_NOPULL;
	hgpio.Speed = GPIO_SPEED_FAST;

	/*Configuring the Orange LED pin*/
	hgpio.Pin = ORANGE_LED_Pin;
	HAL_GPIO_Init(ORANGE_LED_GPIO_Port, &hgpio);

} //eo GPIO_Init::

/**
 * @brief UART Initialization Function
 * @param None
 * @retval None
 * */
void UART_Init(void)
{
	/*Configuring the UART as Tx_Rx for 8N1 with 115200 baud rate*/
	huart.Instance = UART4;

	huart.Init.Mode = UART_MODE_TX_RX;
	huart.Init.BaudRate = 115200;
	huart.Init.Parity = UART_PARITY_NONE;
	huart.Init.StopBits = UART_STOPBITS_1;
	huart.Init.WordLength = UART_WORDLENGTH_8B;
	huart.Init.HwFlowCtl = UART_HWCONTROL_NONE;
	huart.Init.OverSampling = UART_OVERSAMPLING_16;

	if( HAL_UART_Init(&huart) != HAL_OK)
	{
		Error_Handler();
	}

} //eo UART_Init::

void HAL_UART_RxCpltCallback(UART_HandleTypeDef *huart)
{
	if( huart->Instance == UART4)
	{
		/* checking if user entered line feed (LF) */
		if(rcvd_byte == '\r')
		{
			receive_buff[count++] = '\r';
      
      /* Resetting the msg buffer */
			memset(msg, 0, sizeof(msg));
			sprintf(msg, "%s", receive_buff);
      
  		/* Sending data over UART */
			if( HAL_UART_Transmit(huart, (uint8_t*)msg, (uint16_t)strlen(msg), HAL_MAX_DELAY) != HAL_OK)
			{
				Error_Handler();
			}

      /* Resetting the count and receive buffer to keep running the application correctly */
			count = 0;
			memset(receive_buff, 0, sizeof(receive_buff));
		}
		else
		{
			receive_buff[count++] = upper_case(rcvd_byte);
		}

		/* Re-arm to reveive the next character */
		if( HAL_UART_Receive_IT(huart, &rcvd_byte, (uint8_t)1) != HAL_OK)
		{
			Error_Handler();
		}
	}
} //eo HAL_UART_RxCpltCallback::

char upper_case(char data)
{
	if(data >= 'a' && data <= 'z')
	{
		/* means received byte is in lower case */
		data = data - 32;
	}
	return data;
}//eo upper_case::

/**
  * @brief  This function is executed in case of error occurrence.
  * @retval None
  */
void Error_Handler(void)
{
  /* User can add his own implementation to report the HAL error return state */
  __disable_irq();
  while (1)
  {
  }
}

/*
* @note Below code is automatically generated by the STM32CubeMX Software
*/
#ifdef  USE_FULL_ASSERT
/**
  * @brief  Reports the name of the source file and the source line number
  *         where the assert_param error has occurred.
  * @param  file: pointer to the source file name
  * @param  line: assert_param error line source number
  * @retval None
  */
void assert_failed(uint8_t *file, uint32_t line)
{
  /* USER CODE BEGIN 6 */
  /* User can add his own implementation to report the file name and line number,
     ex: printf("Wrong parameters value: file %s on line %d\r\n", file, line) */
  /* USER CODE END 6 */
}
#endif /* USE_FULL_ASSERT */
